### ISSUE TITLE
amazonka-core fails to compile with aeson-2.0.0.0

### ISSUE THREAD

**Issue by phadej** [brendanhay/amazonka#670]
```
[ 5 of 33] Compiling Network.AWS.Data.JSON ( src/Network/AWS/Data/JSON.hs, /codetmp/amazonka-core-1.6.1/dist-newstyle/build/x86_64-linux/ghc-8.6.5/amazonka-core-1.6.1/build/Network/AWS/Data/JSON.o )

src/Network/AWS/Data/JSON.hs:54:23: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘Map.HashMap Text Value’
      Expected type: Map.HashMap Text Value
        Actual type: Object
    • In the second argument of ‘Map.lookup’, namely ‘o’
      In the expression: Map.lookup k o
      In the expression:
        case Map.lookup k o of
          Nothing -> Left $ "key " ++ show k ++ " not present"
          Just v -> parseEither parseJSON v
   |
54 |     case Map.lookup k o of
   |                       ^

src/Network/AWS/Data/JSON.hs:60:23: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘Map.HashMap Text Value’
      Expected type: Map.HashMap Text Value
        Actual type: Object
    • In the second argument of ‘Map.lookup’, namely ‘o’
      In the expression: Map.lookup k o
      In the expression:
        case Map.lookup k o of
          Nothing -> Right Nothing
          Just v -> parseEither parseJSON v
   |
60 |     case Map.lookup k o of
   |  
```

EDIT: I made revision for amazonka-core-1.6.1 and 1.6.0 (e.g. https://hackage.haskell.org/package/amazonka-core-1.6.1/revisions/). I'll check older next.

**Comment by brendanhay** [comment]
Thanks for the headsup, @phadej.

**Comment by endgame** [comment]
This and other similar issues should be caught when we do a check for outdated packages #660 .

Since amazonka-core doesn't exist any more, the metadata revisions are the only fix that makes sense. I'll make a note to check that amazonka itself works with aeson-2.
