### PR TITLE
Fix #449 - Conduit-1.3 support

### LINKED ISSUE #449: conduit-1.3 support
I noticed an open PR [#448 - Add conduit < 1.3 bound](https://github.com/brendanhay/amazonka/pull/448). ~~I take it that it's an interim strategy to get `amazonka` ecosystem to build with the current stackage LTS.~~

Are there plans to move to conduit-1.3 anytime soon? I'd be happy to help. Here's my first stab, [86fa620](https://github.com/naushadh/amazonka/commit/86fa620dfa7fcc4d6d0eb199b4eb4cae43faef21), `amazonka-core` patched and tests pass.

Shall I open a PR?

### PR DESCRIPTION
**Pull request by naushadh**
Fix https://github.com/brendanhay/amazonka/issues/449

### summary of changes
- Replaced deprecated APIs
  - `Source` -> `ConduitM`
  - `=$=` -> `.|`
  - `$$` -> `connect`
  - `ResumableSource` -> `ConduitM` (since `http-client` now returns `ConduitM`)
  - `MonadCatch` -> `MonadThrow` (since `Conduit` no longer offers the former instance)
  - `hoist` -> `transPipe` (since `Conduit` no longer offers `MFunctor` instance)
- Addressed several compiler warnings re: unused imports and shadow bindings
  - Inadvertently ended up re-implementing: https://github.com/brendanhay/amazonka/pull/441
- Added CPP to `amazonka` to build with `http-client < 2.3.0`

### CODE REVIEW

**Comment by naushadh** [comment]
Travis run on my fork has completed already (thanks to caching).
https://travis-ci.org/naushadh/amazonka/builds/357824342

The only failure is from `amazonka-gen` caused by https://github.com/brendanhay/ede/issues/28, for which a fix has been opened: https://github.com/brendanhay/ede/pull/29.

Would love to get `amazonka-*` back on stackage.

**Comment by naushadh** [comment]
As expected, `amazonka-gen` [failed](https://travis-ci.org/brendanhay/amazonka/jobs/357833687) to due above mentioned issue.

`amazonka-ec2` ghc-8.2.2 [failed](https://travis-ci.org/brendanhay/amazonka/jobs/357833753) due to job time limit. Rerun should address this (cached artifacts speedup runtime).

**Comment by domenkozar** [comment]
@brendanhay

**Comment by eikeon** [comment]
@naushadh, Looks like brendanhay/ede#29 needs a Show1 as well? re: 

> [25 of 33] Compiling Gen.AST.Subst    ( src/Gen/AST/Subst.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/amazonka-gen/amazonka-gen-tmp/Gen/AST/Subst.o )
>     
>     /Users/eikeon/amazonka/gen/src/Gen/AST/Subst.hs:114:25: error:
>         • No instance for (Data.Functor.Classes.Show1 ShapeF)
>             arising from a use of ‘safe’
>         • In the first argument of ‘lift’, namely ‘(safe k _shapes)’
>           In a stmt of a 'do' block: x :< s <- lift (safe k _shapes)
>           In the expression:
>             do let k = r ^. refShape
>                x :< s <- lift (safe k _shapes)
>                if | isShared x, d == Input -> do ...
>                   | isShared x -> return r
>                   | otherwise -> do ...
>         |
>     114 |         x :< s <- lift (safe k _shapes)
>         |                         ^^^^^^^^^^^^^^
>     
>

**Comment by naushadh** [comment]
@eikeon Interesting, I guess you tried building `amazonka-gen` with the https://github.com/brendanhay/ede/pull/29 patch? `ShapeF` is defined in `amazonka-gen` (Gen.Types.Service), and `ede` as such has no awareness of it; so it has to be fixed in `amazonka-gen`.

But you're right in that it's similar issue as the `ede` breakage, caused by `Data.Functor.Classes`  changes:
```diff
+ -- base-4.10, Data.Functor.Classes: https://www.stackage.org/haddock/lts-10.10/base-4.10.1.0/Data-Functor-Classes.html#t:Show1
+ class Show1 f where
+    liftShowsPrec :: (Int -> a -> ShowS) -> ([a] -> ShowS) -> Int -> f a -> ShowS

- -- transformers-0.4.3.0, Data.Functor.Classes: https://hackage.haskell.org/package/transformers-0.4.3.0/docs/Data-Functor-Classes.html#t:Show1
- class Show1 f where
-    showsPrec1 :: Show a => Int -> f a -> ShowS
```

**Comment by eikeon** [comment]
@naushadh Yep, I was trying to build everything. Didn't realize I could build just the bits I'm using.

Ah, makes sense re: only similar issue. I didn't dig too deep once I saw it was similar. Hope to see your patches and conduit-3 support find their way upstream. In the mean time I'm trying them out.

**Comment by MichaelXavier** [comment]
@brendanhay Seems like this is a barrier to getting amazonka back on stackage. Do you need additional help with package maintenance? Amazonka seems really widely used and I'm sure some of these people submitting PRs would be happy to share the burden of maintenance.

**Comment by brendanhay** [comment]
Looks good, thanks @naushadh. I'll work on fixing the `amazonka-gen` + `ede` issues once these changes are in `develop`.

**Comment by purcell** [comment]
> I plan to make some changes to the overall structure as well as improve CI + tooling so that ultimately it should be easier for others to contribute and spread out the maintenance/maintership.

I know from hard experience as a maintainer that it can feel like you need a bunch of time just to set things up well for new maintainers so that things will be easier, but it's hard to even get that set-up done when you're slammed for time.

Maybe write some very quick notes/issues about the structure/CI/ tooling changes you'd like to make, and then contributors will not just have more context, but will also have the option to help you make those foundational changes. Even if it takes a few questions back and forth, you might find that one of the very smart people I see dipping into these issues would be able to help move things in exactly the direction you want.
