### ISSUE TITLE
amazonka-core doesn't compile with ghc-7.10

### ISSUE THREAD

**Issue by erikd-ambiata** [brendanhay/amazonka#424]
I'm getting the following compile failure with ghc-7.10:
```
src/Network/AWS/Data/Query.hs:73:47:
    Not in scope: ‘BS8.stripPrefix’
```
The `stripPrefix` function was introduced in bytestring version `0.10.8.0` and ghc-7.10 has version `0.10.6.0`. Since bytestring is a GHC boot library, its not easy (possible?) to replace it.

**Comment by erikd-ambiata** [comment]
Working on a fix for this.

**Comment by gwils** [comment]
@brendanhay Can you please issue a hackage metadata revision so that amazonka-core 1.5.0 doesn't try to build on GHC 7.10? https://matrix.hackage.haskell.org/package/amazonka-core#GHC-7.10/amazonka-core-1.5.0

To achieve this, change the base bound to `base >= 4.9 && < 5`. This will mean users with GHC 7.10 will fall back to amazonka core 1.4 if it is within their bounds. Even if it is not, no install plan is a better user experience than a failing build plan.

I would also appreciate if you could release an amazonka-core 1.5.0.1 that includes this fix, thereby bringing back 7.10 support :)

Thanks a lot!
